export const MOVIES_LOADING = Symbol("MOVIES_LOADING");
export const MOVIES_FETCH_SUCCESS = Symbol("MOVIES_FETCH_SUCCESS");
export const MOVIES_FETCH_FAILURE = Symbol("MOVIES_FETCH_FAILURE");

export const MOVIES_SET_CURRENT_LOADING = Symbol("MOVIES_SET_CURRENT_LOADING");
export const MOVIES_SET_CURRENT = Symbol("MOVIES_SET_CURRENT");

export const MOVIES_SET_CASTS = Symbol("MOVIES_SET_CASTS");

export const MOVIES_CASTS_SET = Symbol("MOVIES_CASTS_SET");
export const MOVIES_CASTS_LOADING = Symbol("MOVIES_CASTS_LOADING");
export const MOVIES_CASTS_FAILURE = Symbol("MOVIES_CASTS_FAILURE");
