<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container56oY9Z0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container56oY9Z0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container56oY9Z0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container56oY9Z0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container56oY9Z0\App_KernelDevDebugContainer([
    'container.build_hash' => '56oY9Z0',
    'container.build_id' => '77cbc0d3',
    'container.build_time' => 1618522925,
], __DIR__.\DIRECTORY_SEPARATOR.'Container56oY9Z0');
