<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT1zdj1q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT1zdj1q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT1zdj1q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT1zdj1q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT1zdj1q\App_KernelDevDebugContainer([
    'container.build_hash' => 'T1zdj1q',
    'container.build_id' => 'fc29db11',
    'container.build_time' => 1618515467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT1zdj1q');
